/* ============================================
   Pleasure Manor вЂ” Category Data
   Auto-generated by sync-thumbs
   ============================================ */

const PM_CATEGORIES = [
  {
    id: 'anal',
    name: 'Anal',
    slug: 'anal',
    folder: 'Anal',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg'],
    videoCount: 49,
    section: 'straight'
  },
  {
    id: 'asian',
    name: 'Asian',
    slug: 'asian',
    folder: 'Asian',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 79,
    section: 'straight'
  },
  {
    id: 'bbc',
    name: 'BBC',
    slug: 'bbc',
    folder: 'BBC',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg'],
    videoCount: 27,
    section: 'straight'
  },
  {
    id: 'big-tits',
    name: 'Big Tits',
    slug: 'big-tits',
    folder: 'Big Tits',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 37,
    section: 'straight'
  },
  {
    id: 'big-toys',
    name: 'Big toys',
    slug: 'big-toys',
    folder: 'Big toys',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg',
      '11.jpg'
    ],
    videoCount: 29,
    section: 'straight'
  },
  {
    id: 'cosplay',
    name: 'Cosplay',
    slug: 'cosplay',
    folder: 'Cosplay',
    thumbs: [
      '1_1.jpg',
      '1_2.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 17,
    section: 'straight'
  },
  {
    id: 'double-penetration',
    name: 'Double Penetration',
    slug: 'double-penetration',
    folder: 'Double Penetration',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg'],
    videoCount: 87,
    section: 'straight'
  },
  {
    id: 'games',
    name: 'Games',
    slug: 'games',
    folder: 'Games',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '4_2.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg'
    ],
    videoCount: 87,
    section: 'straight'
  },
  {
    id: 'hardcore',
    name: 'Hardcore',
    slug: 'hardcore',
    folder: 'Hardcore',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 86,
    section: 'straight'
  },
  {
    id: 'lesbian',
    name: 'Lesbian',
    slug: 'lesbian',
    folder: 'Lesbian',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 70,
    section: 'straight'
  },
  {
    id: 'machine',
    name: 'Machine',
    slug: 'machine',
    folder: 'Machine',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 66,
    section: 'straight'
  },
  {
    id: 'massage',
    name: 'Massage',
    slug: 'massage',
    folder: 'Massage',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 93,
    section: 'straight'
  },
  {
    id: 'stockings',
    name: 'Stockings',
    slug: 'stockings',
    folder: 'Stockings',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 87,
    section: 'straight'
  },
  {
    id: 'tattooed-women',
    name: 'Tattooed Women',
    slug: 'tattooed-women',
    folder: 'Tattooed Women',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg'],
    videoCount: 91,
    section: 'straight'
  },
  {
    id: 'teen',
    name: 'Teen (18+)',
    slug: 'teen',
    folder: 'Teen (18+)',
    thumbs: [
      '1.jpg',
      '2.jpg',
      '3.jpg',
      '4.jpg',
      '5.jpg',
      '6.jpg',
      '7.jpg',
      '8.jpg',
      '9.jpg',
      '10.jpg'
    ],
    videoCount: 19,
    section: 'straight'
  },
  {
    id: 'toys',
    name: 'Toys',
    slug: 'toys',
    folder: 'Toys',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg'],
    videoCount: 23,
    section: 'straight'
  },
  {
    id: 'gay',
    name: 'Gay',
    slug: 'gay',
    folder: 'Gay',
    thumbs: ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg', '16.jpg'],
    videoCount: 16,
    section: 'gay'
  }
];
