# sync-thumbs.ps1
# Scans img/thumbs/categories/ for folders and images,
# regenerates js/categories-data.js

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$thumbsDir = Join-Path $scriptDir 'img\thumbs\categories'
$dataFile  = Join-Path $scriptDir 'js\categories-data.js'
$imageExts = @('.jpg', '.jpeg', '.png', '.avif')

# --- Scan folders ---
$folders = Get-ChildItem -Path $thumbsDir -Directory | Sort-Object Name

$categories = @()
foreach ($folder in $folders) {
    $slug = $folder.Name -replace '\s*\([^)]*\)', ''
    $slug = $slug.Trim().ToLower() -replace '\s+', '-'

    $thumbs = Get-ChildItem -Path $folder.FullName -File |
        Where-Object { $imageExts -contains $_.Extension.ToLower() } |
        Sort-Object {
            $num = [regex]::Match($_.Name, '^\d+').Value
            if ($num) { [double]$num } else { [double]::MaxValue }
        }, Name |
        ForEach-Object { $_.Name }

    $categories += [PSCustomObject]@{
        id     = $slug
        name   = $folder.Name
        slug   = $slug
        folder = $folder.Name
        thumbs = @($thumbs)
    }
}

# --- Generate categories-data.js ---
$nl = [Environment]::NewLine
$sb = [System.Text.StringBuilder]::new()

[void]$sb.Append('/* ============================================' + $nl)
[void]$sb.Append('   Pleasure Manor — Category Data' + $nl)
[void]$sb.Append('   Auto-generated by sync-thumbs' + $nl)
[void]$sb.Append('   ============================================ */' + $nl)
[void]$sb.Append($nl)
[void]$sb.Append('const PM_CATEGORIES = [' + $nl)

for ($i = 0; $i -lt $categories.Count; $i++) {
    $cat = $categories[$i]
    $comma = if ($i -lt $categories.Count - 1) { ',' } else { '' }
    $vidCount = Get-Random -Minimum 15 -Maximum 95

    if ($cat.thumbs.Count -eq 0) {
        $thumbStr = '[]'
    } else {
        $quoted = $cat.thumbs | ForEach-Object { "'$_'" }
        $joined = $quoted -join ', '
        if ($joined.Length -gt 80) {
            $indented = $quoted -join (',' + $nl + '      ')
            $thumbStr = '[' + $nl + '      ' + $indented + $nl + '    ]'
        } else {
            $thumbStr = '[' + $joined + ']'
        }
    }

    $escName = $cat.name -replace "'", "\'"
    $escFolder = $cat.folder -replace "'", "\'"

    [void]$sb.Append('  {' + $nl)
    [void]$sb.Append("    id: '$($cat.id)'," + $nl)
    [void]$sb.Append("    name: '${escName}'," + $nl)
    [void]$sb.Append("    slug: '$($cat.slug)'," + $nl)
    [void]$sb.Append("    folder: '${escFolder}'," + $nl)
    [void]$sb.Append("    thumbs: ${thumbStr}," + $nl)
    [void]$sb.Append("    videoCount: ${vidCount}," + $nl)
    [void]$sb.Append("    section: 'straight'" + $nl)
    [void]$sb.Append("  }${comma}" + $nl)
}

[void]$sb.Append('];' + $nl)

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($dataFile, $sb.ToString(), $utf8NoBom)

# --- Report ---
Write-Host ''
Write-Host "Synced $($categories.Count) categories -> js/categories-data.js" -ForegroundColor Green
foreach ($cat in $categories) {
    Write-Host "  $($cat.folder): $($cat.thumbs.Count) images"
}
Write-Host ''
